### ISSUE TITLE
Traducir la web a varios idiomas

### ISSUE THREAD

**Issue by arg1016** [irg1008/GESPRO_PracticaGestionTareas_2021#55]
Traducir la web a varios idiomas (inglés, alemán, francés)

**Comment by irg1008** [comment]
Hola Jorge, me eh dado cuenta que en inglés hay muchas palabras que no se han traducido correctamente, como "Colmena".

Mira a ver si puedes hacer check de eso, si no añademe como asignado y lo hago yo!!

**Comment by jrg1011** [comment]
Vale vale, ahora lo miramos.

**Comment by jrg1011** [comment]
Estabas mirando una build más vieja!

Cierro

**Comment by irg1008** [comment]
Vale vale, ya lo veo ahora. Genial!
